"""Lecture answerer service using Azure OpenAI for grounded answer generation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Protocol

from app.schemas.lecture_qa import LectureSource

__all__ = [
    "LectureAnswererService",
    "AzureOpenAILectureAnswererService",
    "LectureAnswerDraft",
]


@dataclass
class LectureAnswerDraft:
    """Draft answer generated by Azure OpenAI."""

    answer: str
    confidence: Literal["high", "medium", "low"]
    action_next: str


class LectureAnswererService(Protocol):
    """Interface for generating grounded answers from lecture sources."""

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using provided sources."""
        ...


class AzureOpenAILectureAnswererService:
    """Azure OpenAI-based answerer with source grounding."""

    DEFAULT_MODEL = "gpt-4o"
    DEFAULT_MAX_TOKENS = 1000
    DEFAULT_TEMPERATURE = 0.7
    DEFAULT_TIMEOUT_SECONDS = 30

    def __init__(
        self,
        api_key: str,
        endpoint: str,
        model: str = DEFAULT_MODEL,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        temperature: float = DEFAULT_TEMPERATURE,
        timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        """Initialize Azure OpenAI answerer.

        Args:
            api_key: Azure OpenAI API key
            endpoint: Azure OpenAI endpoint URL
            model: Model deployment name
            max_tokens: Maximum tokens in response
            temperature: Sampling temperature
            timeout_seconds: Request timeout
        """
        self._api_key = api_key
        self._endpoint = endpoint
        self._model = model
        self._max_tokens = max_tokens
        self._temperature = temperature
        self._timeout_seconds = timeout_seconds

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using lecture sources.

        Args:
            question: User question
            lang_mode: Language mode (ja, easy-ja, en)
            sources: Retrieved lecture chunks
            history: Conversation history for context

        Returns:
            Draft answer with confidence and action next
        """
        if not sources:
            # No sources - return low confidence fallback
            return LectureAnswerDraft(
                answer="該当する情報が見つかりませんでした。",
                confidence="low",
                action_next="別の質問をしてください。",
            )

        # Build prompt with sources
        prompt = self._build_prompt(question, lang_mode, sources, history)

        # Call Azure OpenAI (placeholder - real implementation uses openai library)
        answer = await self._call_openai(prompt)

        # Calculate confidence based on sources
        confidence = self._calculate_confidence(sources)

        return LectureAnswerDraft(
            answer=answer,
            confidence=confidence,
            action_next="他にご質問があればどうぞ。",
        )

    def _build_prompt(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str,
    ) -> str:
        """Build grounded answer prompt."""
        sources_text = self._format_sources(sources)

        history_section = f"\n\n会話履歴:\n{history}" if history else ""

        prompt = f"""あなたは講義内容に基づいて質問に答えるアシスタントです。

以下の講義資料（音声転写）のみを使用して、質問に答えてください。

{sources_text}
{history_section}

質問: {question}

回答のガイドライン:
- 講義資料に基づいて回答してください
- 具体的な時間（例: 05:23）を引用して説明してください
- 資料にない情報は「資料に記載がありません」と明示してください
- 簡潔に回答してください（3-5文程度）
"""
        return prompt

    def _format_sources(self, sources: list[LectureSource]) -> str:
        """Format sources for prompt."""
        lines = ["講義資料:"]
        for i, source in enumerate(sources, 1):
            ts = source.timestamp or "??:??"
            lines.append(f"{i}. [{ts}] {source.text}")
        return "\n".join(lines)

    async def _call_openai(self, prompt: str) -> str:
        """Call Azure OpenAI API.

        Note: This is a placeholder implementation.
        Real implementation should use openai.AsyncAzureOpenAI.
        """
        # TODO: Implement real Azure OpenAI call
        # from openai import AsyncAzureOpenAI
        # client = AsyncAzureOpenAI(...)
        # response = await client.chat.completions.create(...)
        # return response.choices[0].message.content

        # Placeholder return
        return "講義資料に基づくと、このトピックについて説明があります。"

    def _calculate_confidence(
        self, sources: list[LectureSource]
    ) -> Literal["high", "medium", "low"]:
        """Calculate confidence based on retrieval quality."""
        if not sources:
            return "low"

        # Count direct hits
        direct_hits = sum(1 for s in sources if s.is_direct_hit)

        # Average BM25 score
        avg_score = sum(s.bm25_score for s in sources) / len(sources) if sources else 0

        if direct_hits >= 3 and avg_score > 2.0:
            return "high"
        elif direct_hits >= 1 and avg_score > 0.5:
            return "medium"
        return "low"
