"""Lecture answerer service using Azure OpenAI for grounded answer generation."""

from __future__ import annotations

import asyncio
import json
import logging
from dataclasses import dataclass
from typing import Literal, Protocol
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

from app.core.azure_openai_config import ValidationResult, validate_openai_config
from app.schemas.lecture_qa import LectureSource
from app.services.observability.llm_usage import LLMUsage, extract_usage

__all__ = [
    "LectureAnswererService",
    "AzureOpenAILectureAnswererService",
    "LectureAnswerDraft",
    "LectureAnswererError",
]

logger = logging.getLogger(__name__)


@dataclass
class LectureAnswerDraft:
    """Draft answer generated by Azure OpenAI."""

    answer: str
    confidence: Literal["high", "medium", "low"]
    action_next: str


class LectureAnswererError(RuntimeError):
    """Raised when Azure OpenAI answer generation fails."""


class LectureAnswererService(Protocol):
    """Interface for generating grounded answers from lecture sources."""

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using provided sources."""
        ...


class AzureOpenAILectureAnswererService:
    """Azure OpenAI-based answerer with source grounding."""

    DEFAULT_MODEL = "gpt-5-nano"
    DEFAULT_MAX_TOKENS = 1000
    DEFAULT_TEMPERATURE = 0.7
    DEFAULT_TIMEOUT_SECONDS = 30
    DEFAULT_API_VERSION = "2024-05-01-preview"
    DEFAULT_ACTION_NEXT = "他にご質問があればどうぞ。"
    NO_SOURCE_ANSWER = "該当する情報が見つかりませんでした。"
    NO_SOURCE_ACTION = "別の質問をしてください。"
    LOCAL_FALLBACK_PREFIX = "講義資料では"
    LOCAL_SNIPPET_MAX_CHARS = 120

    def __init__(
        self,
        api_key: str,
        endpoint: str,
        account_name: str = "",
        model: str = DEFAULT_MODEL,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        temperature: float = DEFAULT_TEMPERATURE,
        timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
        api_version: str = DEFAULT_API_VERSION,
    ) -> None:
        """Initialize Azure OpenAI answerer.

        Args:
            api_key: Azure OpenAI API key
            endpoint: Azure OpenAI endpoint URL
            model: Model deployment name
            max_tokens: Maximum tokens in response
            temperature: Sampling temperature
            timeout_seconds: Request timeout
        """
        self._api_key = api_key
        self._endpoint = endpoint
        self._model = model
        self._max_tokens = max_tokens
        self._temperature = temperature
        self._timeout_seconds = timeout_seconds
        self._api_version = api_version
        self._last_usage: LLMUsage | None = None
        self._validation = self._validate_configuration(account_name=account_name)
        if not self._validation.is_valid:
            logger.warning(
                "azure_openai_lecture_answer_config_invalid reason=%s",
                self._validation.reason,
            )

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using lecture sources.

        Args:
            question: User question
            lang_mode: Language mode (ja, easy-ja, en)
            sources: Retrieved lecture chunks
            history: Conversation history for context

        Returns:
            Draft answer with confidence and action next
        """
        if not sources:
            return LectureAnswerDraft(
                answer=self.NO_SOURCE_ANSWER,
                confidence="low",
                action_next=self.NO_SOURCE_ACTION,
            )

        prompt = self._build_prompt(question, lang_mode, sources, history)
        confidence = self._calculate_confidence(sources)

        if not self._is_azure_openai_ready():
            return LectureAnswerDraft(
                answer=self._build_local_fallback_answer(sources),
                confidence=confidence,
                action_next=self.DEFAULT_ACTION_NEXT,
            )

        answer = await self._call_openai(prompt)
        if not answer.strip():
            raise LectureAnswererError("empty answer from Azure OpenAI")

        return LectureAnswerDraft(
            answer=answer,
            confidence=confidence,
            action_next=self.DEFAULT_ACTION_NEXT,
        )

    def _build_prompt(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str,
    ) -> str:
        """Build grounded answer prompt."""
        sources_text = self._format_sources(sources)

        history_section = f"\n\n会話履歴:\n{history}" if history else ""

        prompt = f"""あなたは講義内容に基づいて質問に答えるアシスタントです。

以下の講義資料（音声転写）のみを使用して、質問に答えてください。

{sources_text}
{history_section}

質問: {question}

回答のガイドライン:
- 講義資料に基づいて回答してください
- 具体的な時間（例: 05:23）を引用して説明してください
- 資料にない情報は「資料に記載がありません」と明示してください
- 簡潔に回答してください（3-5文程度）
"""
        return prompt

    def _format_sources(self, sources: list[LectureSource]) -> str:
        """Format sources for prompt."""
        lines = ["講義資料:"]
        for i, source in enumerate(sources, 1):
            ts = source.timestamp or "??:??"
            lines.append(f"{i}. [{ts}] {source.text}")
        return "\n".join(lines)

    async def _call_openai(self, prompt: str) -> str:
        """Call Azure OpenAI chat completion endpoint.

        Raises:
            LectureAnswererError: If the Azure OpenAI call fails.
        """
        url = self._build_chat_completion_url()
        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a grounded lecture QA assistant. "
                        "Answer only with provided lecture evidence."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            "max_completion_tokens": self._max_tokens,
        }
        body = json.dumps(payload).encode("utf-8")
        request = Request(
            url=url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "api-key": self._api_key,
            },
            method="POST",
        )

        def _run_request() -> str:
            with urlopen(request, timeout=self._timeout_seconds) as response:
                return response.read().decode("utf-8")

        try:
            raw = await asyncio.to_thread(_run_request)
            response_json = json.loads(raw)
            self._last_usage = extract_usage(response_json)
            return self._extract_content(response_json).strip()
        except HTTPError as exc:
            logger.warning(
                "azure_openai_answer_http_error status=%s",
                getattr(exc, "code", "unknown"),
            )
            raise LectureAnswererError("azure openai answer request failed") from exc
        except URLError as exc:
            logger.warning("azure_openai_answer_network_error")
            raise LectureAnswererError("azure openai answer network failure") from exc
        except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
            logger.warning("azure_openai_answer_parse_error")
            raise LectureAnswererError("azure openai answer parse failure") from exc

    def _is_azure_openai_ready(self) -> bool:
        """Return whether Azure OpenAI runtime call should be attempted."""
        return self._validation.is_valid

    def _build_chat_completion_url(self) -> str:
        endpoint = self._validation.normalized_endpoint.rstrip("/")
        deployment = quote(self._model.strip(), safe="")
        return (
            f"{endpoint}/openai/deployments/{deployment}/chat/completions"
            f"?api-version={self._api_version}"
        )

    def _validate_configuration(self, *, account_name: str) -> ValidationResult:
        return validate_openai_config(
            api_key=self._api_key,
            endpoint=self._endpoint,
            deployment=self._model,
            account_name=account_name,
        )

    def _extract_content(self, response_json: dict[str, object]) -> str:
        choices = response_json.get("choices")
        if not isinstance(choices, list) or not choices:
            raise ValueError("missing choices")
        first_choice = choices[0]
        if not isinstance(first_choice, dict):
            raise ValueError("invalid choice payload")
        first_choice_dict = {str(key): value for key, value in first_choice.items()}
        message = first_choice_dict.get("message")
        if not isinstance(message, dict):
            raise ValueError("missing message")
        message_dict = {str(key): value for key, value in message.items()}
        content = message_dict.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            text_parts = []
            for part in content:
                if not isinstance(part, dict):
                    continue
                part_dict = {str(key): value for key, value in part.items()}
                text = part_dict.get("text")
                if isinstance(text, str) and text.strip():
                    text_parts.append(text.strip())
            if text_parts:
                return "\n".join(text_parts)
        raise ValueError("missing content")

    def _build_local_fallback_answer(self, sources: list[LectureSource]) -> str:
        evidence = [source for source in sources if source.is_direct_hit] or sources
        snippets = [
            self._sanitize_snippet(source.text)
            for source in evidence[:2]
            if source.text.strip()
        ]
        if not snippets:
            return self.NO_SOURCE_ANSWER
        if len(snippets) == 1:
            return f"{self.LOCAL_FALLBACK_PREFIX}「{snippets[0]}」と説明されています。"
        return (
            f"{self.LOCAL_FALLBACK_PREFIX}「{snippets[0]}」および「{snippets[1]}」"
            "の内容が関連しています。"
        )

    def _sanitize_snippet(self, text: str) -> str:
        snippet = text.strip().replace("\n", " ")
        if len(snippet) <= self.LOCAL_SNIPPET_MAX_CHARS:
            return snippet
        return f"{snippet[: self.LOCAL_SNIPPET_MAX_CHARS]}..."

    def _calculate_confidence(
        self, sources: list[LectureSource]
    ) -> Literal["high", "medium", "low"]:
        """Calculate confidence based on retrieval quality."""
        if not sources:
            return "low"

        # Count direct hits
        direct_hits = sum(1 for s in sources if s.is_direct_hit)

        # Average BM25 score
        avg_score = sum(s.bm25_score for s in sources) / len(sources) if sources else 0

        if direct_hits >= 3 and avg_score > 2.0:
            return "high"
        elif direct_hits >= 1 and avg_score > 0.5:
            return "medium"
        return "low"
