"""Lecture answerer service using Azure OpenAI for grounded answer generation."""

from __future__ import annotations

import asyncio
import json
import logging
import re
from dataclasses import dataclass
from time import monotonic
from typing import Literal, Protocol
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

from app.core.azure_openai_config import ValidationResult, validate_openai_config
from app.schemas.lecture_qa import LectureSource
from app.services.observability.llm_usage import LLMUsage, extract_usage

__all__ = [
    "LectureAnswererService",
    "AzureOpenAILectureAnswererService",
    "LectureAnswerDraft",
    "LectureAnswererError",
]

logger = logging.getLogger(__name__)


@dataclass
class LectureAnswerDraft:
    """Draft answer generated by Azure OpenAI."""

    answer: str
    confidence: Literal["high", "medium", "low"]
    action_next: str


class LectureAnswererError(RuntimeError):
    """Raised when Azure OpenAI answer generation fails."""


class LectureAnswererService(Protocol):
    """Interface for generating grounded answers from lecture sources."""

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using provided sources."""
        ...


class AzureOpenAILectureAnswererService:
    """Azure OpenAI-based answerer with source grounding."""

    DEFAULT_MODEL = "gpt-5-nano"
    DEFAULT_MAX_TOKENS = 1000
    DEFAULT_TEMPERATURE = 0.7
    DEFAULT_TIMEOUT_SECONDS = 30
    DEFAULT_MAX_RETRIES = 4
    DEFAULT_RETRY_DELAY_SECONDS = 1.0
    DEFAULT_MIN_REQUEST_INTERVAL_SECONDS = 0.35
    DEFAULT_MAX_RETRY_AFTER_SECONDS = 2.0
    DEFAULT_API_VERSION = "2024-05-01-preview"
    DEFAULT_ACTION_NEXT = "他にご質問があればどうぞ。"
    DEFAULT_ACTION_NEXT_EN = "Feel free to ask another question."
    NO_SOURCE_ANSWER = "該当する情報が見つかりませんでした。"
    NO_SOURCE_ANSWER_EN = "No relevant information was found in the lecture materials."
    NO_SOURCE_ACTION = "別の質問をしてください。"
    NO_SOURCE_ACTION_EN = "Please ask another question."
    LOCAL_FALLBACK_PREFIX = "講義資料では"
    LOCAL_FALLBACK_PREFIX_EN = "The lecture materials explain that"
    LOCAL_SNIPPET_MAX_CHARS = 120

    def __init__(
        self,
        api_key: str,
        endpoint: str,
        account_name: str = "",
        model: str = DEFAULT_MODEL,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        temperature: float = DEFAULT_TEMPERATURE,
        timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
        max_retries: int = DEFAULT_MAX_RETRIES,
        retry_delay_seconds: float = DEFAULT_RETRY_DELAY_SECONDS,
        min_request_interval_seconds: float = DEFAULT_MIN_REQUEST_INTERVAL_SECONDS,
        max_retry_after_seconds: float = DEFAULT_MAX_RETRY_AFTER_SECONDS,
        api_version: str = DEFAULT_API_VERSION,
    ) -> None:
        """Initialize Azure OpenAI answerer.

        Args:
            api_key: Azure OpenAI API key
            endpoint: Azure OpenAI endpoint URL
            model: Model deployment name
            max_tokens: Maximum tokens in response
            temperature: Sampling temperature
            timeout_seconds: Request timeout
        """
        self._api_key = api_key
        self._endpoint = endpoint
        self._model = model
        self._max_tokens = max_tokens
        self._temperature = temperature
        self._timeout_seconds = timeout_seconds
        self._max_retries = max(0, max_retries)
        self._retry_delay_seconds = max(0.0, retry_delay_seconds)
        self._min_request_interval_seconds = max(0.0, min_request_interval_seconds)
        self._max_retry_after_seconds = max(0.0, max_retry_after_seconds)
        self._request_lock = asyncio.Lock()
        self._last_request_started_at = 0.0
        self._api_version = api_version
        self._last_usage: LLMUsage | None = None
        self._validation = self._validate_configuration(account_name=account_name)
        if not self._validation.is_valid:
            logger.warning(
                "azure_openai_lecture_answer_config_invalid reason=%s",
                self._validation.reason,
            )

    async def answer(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str = "",
    ) -> LectureAnswerDraft:
        """Generate grounded answer using lecture sources.

        Args:
            question: User question
            lang_mode: Language mode (ja, easy-ja, en)
            sources: Retrieved lecture chunks
            history: Conversation history for context

        Returns:
            Draft answer with confidence and action next
        """
        target_language = self._resolve_response_language(
            question=question,
            lang_mode=lang_mode,
        )

        if not sources:
            return LectureAnswerDraft(
                answer=self._no_source_answer(target_language),
                confidence="low",
                action_next=self._no_source_action(target_language),
            )

        prompt = self._build_prompt(question, target_language, sources, history)
        confidence = self._calculate_confidence(sources)

        if not self._is_azure_openai_ready():
            return LectureAnswerDraft(
                answer=self._build_local_fallback_answer(sources, target_language),
                confidence=confidence,
                action_next=self._default_action_next(target_language),
            )

        answer = await self._call_openai(prompt, target_language)
        if not answer.strip():
            logger.warning(
                "azure_openai_answer_empty_response model=%s lang=%s sources=%s",
                self._model,
                target_language,
                len(sources),
            )
            raise LectureAnswererError("empty answer from Azure OpenAI")

        return LectureAnswerDraft(
            answer=answer,
            confidence=confidence,
            action_next=self._default_action_next(target_language),
        )

    def _build_prompt(
        self,
        question: str,
        lang_mode: str,
        sources: list[LectureSource],
        history: str,
    ) -> str:
        """Build grounded answer prompt."""
        target_language = self._resolve_response_language(
            question=question,
            lang_mode=lang_mode,
        )
        if target_language == "en":
            sources_text = self._format_sources(sources, heading="Lecture sources:")
            history_section = (
                f"\n\nConversation history:\n{history}" if history else ""
            )
            return f"""You are a grounded lecture QA assistant.

Use only the lecture transcript sources below to answer the question.

{sources_text}
{history_section}

Question: {question}

Answer requirements:
- Use only the lecture sources above
- Use only the minimum evidence needed to answer the question
- Cite concrete timestamps when available (e.g., 05:23)
- If a detail is missing from sources, explicitly say it is not in the materials
- Keep the answer concise (1-3 sentences for fact questions, 3-5 sentences otherwise)
- Response language: English only
"""

        sources_text = self._format_sources(sources)
        language_instruction = self._language_instruction(target_language)
        history_section = f"\n\n会話履歴:\n{history}" if history else ""

        return f"""あなたは講義内容に基づいて質問に答えるアシスタントです。

以下の講義資料（音声転写）のみを使用して、質問に答えてください。

{sources_text}
{history_section}

質問: {question}

回答のガイドライン:
- 講義資料に基づいて回答してください
- 回答に必要な根拠のみ使ってください（不要な引用はしない）
- 具体的な時間（例: 05:23）を引用して説明してください
- 資料にない情報は「資料に記載がありません」と明示してください
- 簡潔に回答してください（事実質問は1-3文、それ以外は3-5文程度）
- 回答言語: {language_instruction}
"""

    def _language_instruction(self, target_language: Literal["ja", "easy-ja", "en"]) -> str:
        if target_language == "en":
            return "English only"
        if target_language == "easy-ja":
            return "やさしい日本語"
        return "日本語"

    def _resolve_response_language(
        self,
        question: str,
        lang_mode: str,
    ) -> Literal["ja", "easy-ja", "en"]:
        if lang_mode == "en":
            return "en"
        if self._is_english_question(question):
            return "en"
        if lang_mode == "easy-ja":
            return "easy-ja"
        return "ja"

    @staticmethod
    def _is_english_question(question: str) -> bool:
        stripped = question.strip()
        if not stripped:
            return False
        has_latin = bool(re.search(r"[A-Za-z]", stripped))
        has_japanese = bool(re.search(r"[ぁ-んァ-ン一-龥]", stripped))
        return has_latin and not has_japanese

    def _format_sources(
        self,
        sources: list[LectureSource],
        *,
        heading: str = "講義資料:",
    ) -> str:
        """Format sources for prompt."""
        lines = [heading]
        for i, source in enumerate(sources, 1):
            ts = source.timestamp or "??:??"
            lines.append(f"{i}. [{ts}] {source.text}")
        return "\n".join(lines)

    async def _call_openai(
        self,
        prompt: str,
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        """Call Azure OpenAI chat completion endpoint.

        Raises:
            LectureAnswererError: If the Azure OpenAI call fails.
        """
        url = self._build_chat_completion_url()
        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": self._system_instruction(target_language),
                },
                {"role": "user", "content": prompt},
            ],
            "max_completion_tokens": self._max_tokens,
        }
        body = json.dumps(payload).encode("utf-8")
        request = Request(
            url=url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "api-key": self._api_key,
            },
            method="POST",
        )

        def _run_request() -> str:
            with urlopen(request, timeout=self._timeout_seconds) as response:
                return response.read().decode("utf-8")

        last_http_error: HTTPError | None = None
        for attempt in range(self._max_retries + 1):
            try:
                await self._wait_for_request_slot()
                raw = await asyncio.to_thread(_run_request)
                response_json = json.loads(raw)
                self._last_usage = extract_usage(response_json)
                return self._extract_content(response_json).strip()
            except HTTPError as exc:
                last_http_error = exc
                status_code = int(getattr(exc, "code", 0) or 0)
                retry_after_seconds = self._retry_after_seconds(exc)
                should_retry = status_code == 429 and attempt < self._max_retries
                response_snippet = self._http_error_payload_snippet(exc)
                logger.warning(
                    "azure_openai_answer_http_error status=%s reason=%s attempt=%s max_retries=%s will_retry=%s retry_after=%s response_snippet=%r",
                    getattr(exc, "code", "unknown"),
                    getattr(exc, "reason", "unknown"),
                    attempt,
                    self._max_retries,
                    should_retry,
                    retry_after_seconds,
                    response_snippet,
                )
                if should_retry:
                    await asyncio.sleep(self._compute_retry_delay(exc, attempt))
                    continue
                raise LectureAnswererError("azure openai answer request failed") from exc
            except URLError as exc:
                logger.warning("azure_openai_answer_network_error")
                raise LectureAnswererError("azure openai answer network failure") from exc
            except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
                logger.warning("azure_openai_answer_parse_error")
                raise LectureAnswererError("azure openai answer parse failure") from exc

        raise LectureAnswererError("azure openai answer request failed") from last_http_error

    async def _wait_for_request_slot(self) -> None:
        if self._min_request_interval_seconds <= 0:
            return
        async with self._request_lock:
            now = monotonic()
            elapsed = now - self._last_request_started_at
            remaining = self._min_request_interval_seconds - elapsed
            if remaining > 0:
                await asyncio.sleep(remaining)
            self._last_request_started_at = monotonic()

    def _compute_retry_delay(self, exc: HTTPError, attempt: int) -> float:
        retry_after = self._retry_after_seconds(exc)
        if retry_after is not None:
            return min(retry_after, self._max_retry_after_seconds)
        return self._retry_delay_seconds * (2**attempt)

    @staticmethod
    def _retry_after_seconds(exc: HTTPError) -> float | None:
        headers = getattr(exc, "headers", None)
        if headers is None:
            return None
        raw_retry_after = headers.get("Retry-After")
        if raw_retry_after is None:
            return None
        try:
            retry_after = float(str(raw_retry_after).strip())
            if retry_after < 0:
                return None
            return retry_after
        except ValueError:
            return None

    @staticmethod
    def _http_error_payload_snippet(exc: HTTPError, max_chars: int = 240) -> str:
        try:
            payload = exc.read()
            if not payload:
                return ""
            if isinstance(payload, bytes):
                text = payload.decode("utf-8", errors="replace")
            else:
                text = str(payload)
            compact = re.sub(r"\s+", " ", text).strip()
            return compact[:max_chars]
        except Exception:
            return ""

    def _system_instruction(
        self,
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        if target_language == "en":
            return (
                "You are a grounded lecture QA assistant. "
                "Use only provided lecture evidence. "
                "Respond in English only and never switch to Japanese."
            )
        return (
            "You are a grounded lecture QA assistant. "
            "Answer only with provided lecture evidence."
        )

    def _is_azure_openai_ready(self) -> bool:
        """Return whether Azure OpenAI runtime call should be attempted."""
        return self._validation.is_valid

    def _build_chat_completion_url(self) -> str:
        endpoint = self._validation.normalized_endpoint.rstrip("/")
        deployment = quote(self._model.strip(), safe="")
        return (
            f"{endpoint}/openai/deployments/{deployment}/chat/completions"
            f"?api-version={self._api_version}"
        )

    def _validate_configuration(self, *, account_name: str) -> ValidationResult:
        return validate_openai_config(
            api_key=self._api_key,
            endpoint=self._endpoint,
            deployment=self._model,
            account_name=account_name,
        )

    def _extract_content(self, response_json: dict[str, object]) -> str:
        choices = response_json.get("choices")
        if not isinstance(choices, list) or not choices:
            raise ValueError("missing choices")
        first_choice = choices[0]
        if not isinstance(first_choice, dict):
            raise ValueError("invalid choice payload")
        first_choice_dict = {str(key): value for key, value in first_choice.items()}
        message = first_choice_dict.get("message")
        if not isinstance(message, dict):
            raise ValueError("missing message")
        message_dict = {str(key): value for key, value in message.items()}
        content = message_dict.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            text_parts = []
            for part in content:
                if not isinstance(part, dict):
                    continue
                part_dict = {str(key): value for key, value in part.items()}
                text = part_dict.get("text")
                if isinstance(text, str) and text.strip():
                    text_parts.append(text.strip())
            if text_parts:
                return "\n".join(text_parts)
        raise ValueError("missing content")

    def _build_local_fallback_answer(
        self,
        sources: list[LectureSource],
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        evidence = [source for source in sources if source.is_direct_hit] or sources
        snippets = [
            self._sanitize_snippet(source.text)
            for source in evidence[:2]
            if source.text.strip()
        ]
        if not snippets:
            return self._no_source_answer(target_language)
        if len(snippets) == 1:
            if target_language == "en":
                return f"{self.LOCAL_FALLBACK_PREFIX_EN} \"{snippets[0]}\"."
            return f"{self.LOCAL_FALLBACK_PREFIX}「{snippets[0]}」と説明されています。"
        if target_language == "en":
            return (
                f"{self.LOCAL_FALLBACK_PREFIX_EN} \"{snippets[0]}\" and "
                f"\"{snippets[1]}\"."
            )
        return (
            f"{self.LOCAL_FALLBACK_PREFIX}「{snippets[0]}」および「{snippets[1]}」"
            "の内容が関連しています。"
        )

    def _default_action_next(
        self,
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        if target_language == "en":
            return self.DEFAULT_ACTION_NEXT_EN
        return self.DEFAULT_ACTION_NEXT

    def _no_source_answer(
        self,
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        if target_language == "en":
            return self.NO_SOURCE_ANSWER_EN
        return self.NO_SOURCE_ANSWER

    def _no_source_action(
        self,
        target_language: Literal["ja", "easy-ja", "en"],
    ) -> str:
        if target_language == "en":
            return self.NO_SOURCE_ACTION_EN
        return self.NO_SOURCE_ACTION

    def _sanitize_snippet(self, text: str) -> str:
        snippet = text.strip().replace("\n", " ")
        if len(snippet) <= self.LOCAL_SNIPPET_MAX_CHARS:
            return snippet
        return f"{snippet[: self.LOCAL_SNIPPET_MAX_CHARS]}..."

    def _calculate_confidence(
        self, sources: list[LectureSource]
    ) -> Literal["high", "medium", "low"]:
        """Calculate confidence based on retrieval quality."""
        if not sources:
            return "low"

        # Count direct hits
        direct_hits = sum(1 for s in sources if s.is_direct_hit)

        # Average BM25 score
        avg_score = sum(s.bm25_score for s in sources) / len(sources) if sources else 0

        if direct_hits >= 3 and avg_score > 2.0:
            return "high"
        elif direct_hits >= 1 and avg_score > 0.5:
            return "medium"
        return "low"
